# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50613947916f6669728d374491711b0e709c055cd599b313d66e128d139f2d6fe43d4e888a7cba76d7da9d64fbcbe6084c469c366f34f85c7446bcd41b53d46c

test:
  secret_key_base: 55ad718549788fdb18b5c2cb3fb83dff3981c47c73dfdf94f6aab17d0728944cc9c29cf2fc7d337020bf3cb43f977e9736b6aed31426de00d123b82cf50cef5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
